
name: campus_marketplace_w7

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Dependencies เดิมจากสัปดาห์ที่ 6-7
  http: ^1.6.0
  provider: ^6.1.5+1
  image_picker: ^1.2.3

  # Dependencies สำหรับ Drift
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Dependencies สำหรับสร้างโค้ดฐานข้อมูล
  drift_dev: ^2.20.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true